name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.3
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  archive: ^3.3.5
  collection:
  crypto: ^3.0.2
  dartx: ^1.1.0
  dfunc: ^0.8.0+1
  equatable: ^2.0.5
  fimber: ^0.6.6
  http: ^0.13.5
  image: ^4.0.8
  intl: ^0.18.0
  meta: ^1.8.0
  path: ^1.8.3
  universal_io: ^2.0.4
  xml: ^6.2.2
  mno_commons:
    path: ../commons

dev_dependencies:
  image_compare: ^1.1.2
  lints: ^2.0.1
  test: ^1.22.2
