name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mno_streamer:
    path: ../
  dfunc: ^0.8.1
  universal_io: ^2.0.4
  xml: ^6.2.2

dev_dependencies:
  lints: ^2.0.1
