name: iridium_app
description: A Flutter app for eBooks

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  flutter_icons: ^1.1.0
  xml2json: ^5.3.1
  fluttertoast: ^8.0.8
  cached_network_image: ^3.1.0+1
  uuid: ^3.0.5
  objectdb: ^1.2.1+1
  epub_viewer: ^0.2.4
  path_provider: ^2.0.7
  dio: ^4.0.3
  permission_handler: ^8.3.0
  google_fonts: ^2.1.0
  flutter_spinkit: ^5.1.0

  mno_opds: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
