name: mno_navigator
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.1
  dartx: ^0.8.0
  dfunc: ^0.7.2
  equatable: ^2.0.3
  fimber: ^0.6.1
  flutter_bloc: ^7.3.3
  flutter_inappwebview: ^5.3.2
  photo_view: ^0.13.0
  preload_page_view: ^0.1.6
  universal_io: ^2.0.4
  webview_flutter: ^2.3.1

  mno_commons:
    path: ../mno_commons_dart
  mno_server:
    path: ../mno_server_dart
  mno_shared:
    path: ../mno_shared_dart
  mno_streamer:
    path: ../mno_streamer_dart

dev_dependencies:
  test: ^1.19.3
  lints: ^1.0.1

flutter:

  assets:
    - assets/xpub-assets/
    - assets/xpub-shared-js/
    - assets/xpub-js/
    - assets/xpub-js/controllers/
    - assets/xpub-js/model/
    - assets/xpub-js/utils/
