name: mno_lcp
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  collection: #^1.17.0
  crypto: ^3.0.2
  dartx: ^1.1.0
  device_info_plus: ^8.2.1
  dfunc: ^0.8.2
  ffi: ^2.0.1
  fimber: ^0.6.6
  flutter_archive: ^5.0.0
  intl: ^0.17.0
  mno_fsm: ^0.1.2
  multiple_localization: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.14
  shared_preferences: #^2.0.17
  sqflite: ^2.2.7
  universal_io: ^2.2.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.1

assets:
  - assets/
