name: mno_lcp
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dartx: ^1.2.0
  device_info_plus: ^9.1.1
  dfunc: ^0.9.0
  ffi: 2.1.0
  fimber: ^0.7.0
  flutter_archive: ^6.0.0
  mno_fsm: ^0.2.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  universal_io: ^2.2.2
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  multiple_localization: ^0.4.0
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dependency_overrides:
  intl: ^0.19.0 # multiple_localization 0.3.0 requires intl 0.17.0
  meta: ^1.11.0 # mno_shared 0.1.3 requires meta 1.9.1
  collection: ^1.18.0 # universal_io 2.2.1 requires it

dev_dependencies:
  test: ^1.25.1
  lints: ^3.0.0

assets:
  - assets/
