name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mno_lcp:
    path: ../
  mno_shared:
    path: ../../shared

dependency_overrides:
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
