name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mno_lcp:
    path: ../
  mno_shared:
    path: ../../shared

dependency_overrides:
  intl: ^0.18.1 # multiple_localization 0.3.0 requires intl 0.17.0
  meta: ^1.9.1 # mno_shared 0.1.3 requires meta 1.9.1
  collection: ^1.17.2 # universal_io 2.2.1 requires it
