name: mno_commons
description: This package provide utilities (JSON, io, Href, UriTemplate, etc...) for other mno_xxx packages.
version: 0.1.2
homepage: https://github.com/Mantano/mno_commons_dart
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.10
  crypto: ^3.0.3
  dartx: ^1.2.0
  dfunc: ^0.9.0
  fimber: ^0.7.0
  path: ^1.9.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
