name: mno_opds
description: Contains OPDS1 and OPDS2 parsers using OPDS classes provided by mno_shared.
version: 0.1.1
homepage: https://github.com/Mantano/mno_opds_dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dartx: ^1.1.0
  dfunc: ^0.8.1
  fimber: ^0.6.6
  http: ^0.13.5
  universal_io: ^2.0.4
  xml: ^6.2.2
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
