name: iridium_reader_widget
description: Plug and play ebook reader widget
version: 0.0.1
publish_to: none
homepage: https://iridium.rocks

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  mno_commons:
    path: ../components/commons
  mno_navigator:
    path: ../components/navigator
  mno_opds:
    path: ../components/opds
  mno_server:
    path: ../components/server
  mno_shared:
    path: ../components/shared
  mno_streamer:
    path: ../components/streamer
  #  cupertino_icons: ^1.0.5
  dartx: ^1.2.0
  dfunc: ^0.9.0
  flutter_bloc: ^8.1.3
  flutter_fimber: ^0.7.1
  flutter_inappwebview: ^6.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master # branch name

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.18.0
  path: ^1.9.0
  meta: ^1.11.0 # mno_shared 0.1.3 requires meta 1.9.1

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
