name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mno_server:
    path: ../
  mno_shared:
    path: ../../shared
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^2.0.0

dependency_overrides:
  path: ^1.8.3
